---
title: "Analysis"
author: "Bertrand Wilden"
date: "1/3/2021"
output: html_document
---

```{r Libraries, message=F}
library(tidyverse)
library(ggthemes)
library(caret)
library(here)
library(wru)
library(gridExtra)
library(grid)
```


```{r Data Loading, message=F}
census_api <- "5e4c2b8438222753a7f4753fa78855eca73b9950"

load(file = here("data", "census_fl.RData"))
load(file = here("data", "census_nc.RData"))
load(file = here("data", "nc_fl.rda"))
load(file = here("data", "nc_fl_wru.rda"))
load(file = here("data", "contribs_bper_preds.rda"))
load(file = here("data", "contribs_wru_preds.rda"))


source(here("R", "prep", "clean_race_data.R"))
source(here("R", "funcs", "predict_ethnorace.R"))
source(here("R", "funcs", "classify_and_report.R"))
```

```{r}
gen_fig1_data <- function(df, method) {
  df <- df %>% 
    sample_n(1e6) %>% 
    mutate(pred_prob = case_when(pred_race == "black" ~ prob_black,
                                 pred_race == "api" ~ prob_api,
                                 pred_race == "white" ~ prob_white,
                                 pred_race == "hispanic" ~ prob_hispanic,
                                 TRUE ~ NA_real_),
           method := method) %>% 
    select(pred_prob, method)
  
  return(df)
}

fig1 <- rbind(gen_fig1_data(contribs_bper_preds, "bper"),
              gen_fig1_data(contribs_wru_preds, "wru"))
```


```{r}
fig1 %>% 
  ggplot(aes(x = pred_prob)) +
  geom_density() +
  facet_wrap(~ method)

```


```{r}
gen_fig2_data <- function(df, method) {
  
  black_totals <- df %>%
    filter(pred_race == "black") %>%
    summarise(across(contains("amount_"), ~ sum(.))) %>% 
    pivot_longer(cols = everything(), names_to = "year", values_to = "total") %>% 
    mutate(race = "black")

  hispanic_totals <- df %>%
    filter(pred_race == "hispanic") %>%
    summarise(across(contains("amount_"), ~ sum(.))) %>% 
    pivot_longer(cols = everything(), names_to = "year", values_to = "total") %>% 
    mutate(race = "hispanic")

  api_totals <- df %>%
    filter(pred_race == "api") %>%
    summarise(across(contains("amount_"), ~ sum(.))) %>% 
    pivot_longer(cols = everything(), names_to = "year", values_to = "total") %>% 
    mutate(race = "api")

  white_totals <- df %>%
    filter(pred_race %notin% c("black", "hispanic", "api")) %>%
    summarise(across(contains("amount_"), ~ sum(.))) %>% 
    pivot_longer(cols = everything(), names_to = "year", values_to = "total") %>% 
    mutate(race = "white")
  
  contribs_props <- rbind(black_totals, hispanic_totals, 
                          api_totals, white_totals) %>% 
    group_by(year) %>% 
    mutate(share = total / sum(total),
           year = str_remove(year, "amount_"),
           method := method)
  
  return(contribs_props)
}

fig2 <- rbind(
  gen_fig2_data(contribs_bper_preds, "bper"),
  gen_fig2_data(contribs_wru_preds, "wru")) %>% 
  filter(race != "white") %>%
  mutate(year = as.numeric(year),
         method = factor(method, levels = c("wru", "bper")))

fig2
```


```{r}
fig2 %>%
  ggplot() +
  geom_col(aes(x = year, y = share, fill = race)) +
  theme_classic() +
  labs(x = 'Year', y = 'Prop. of Contributions') +
  scale_fill_grey(labels = c("Asian", "Black", "Hispanic")) +
  theme(legend.title = element_blank(), legend.position = "bottom") +
  theme(text = element_text(size = 20)) +
  facet_wrap(~ method)
```

```{r}
contribs_wru_preds %>% 
  filter(pred_race == "hispanic") %>% 
  summarise(across(contains("amount_"), ~ sum(.))) %>% 
  pivot_longer(cols = everything(), names_to = "year", values_to = "total") %>% 
  mutate(year = as.numeric(str_remove(year, "amount_"))) %>% 
  ggplot(aes(x = year, y = total)) +
  geom_point() +
  labs(title = "Latino Campaign Contributions by Date")
ggsave(filename = here("plots", "latino_contributions.png"))
```

```{r}
contribs_wru_preds %>% 
  summarise(across(contains("amount_"), ~ sum(. > 0))) %>% 
  pivot_longer(cols = everything(), names_to = "year", values_to = "total") %>% 
  mutate(year = as.numeric(str_remove(year, "amount_"))) %>% 
  ggplot(aes(x = year, y = total)) +
  geom_point() +
  labs(title = "Total Campaign Contributions by Date")
ggsave(filename = here("plots", "total_contributions.png"))
```



```{r}
gen_fig3_data <- function(df, method) {
  contrib_table <- prop.table(table(df$pred_race))
  
  contrib_props <- tibble(
    race = c("Black", "Latino", "Asian"),
    share = c(contrib_table["black"], contrib_table["hispanic"], contrib_table["api"]),
    type := method
  )
  
  return(contrib_props)
}

pop_race_stats <- read_csv(here("sahn_grumbach", "Population Race Statistics (Pew).csv")) %>% 
  filter(race != "White",
         type %in% c("Registered Voters", "Members of Congress")) %>% 
  select(race, share = pct.money, type)

fig3 <- rbind(
  gen_fig3_data(contribs_bper_preds, "bper Contributors"),
  gen_fig3_data(contribs_wru_preds, "wru Contributors"),
  pop_race_stats) %>% 
  mutate(type = factor(type, levels = c("Registered Voters", "Members of Congress",
                                        "wru Contributors", "bper Contributors")),
         race = case_when(race == "Latino" ~ "Hispanic",
                          TRUE ~ race))

fig3
```

```{r}
fig3 %>% 
  ggplot(aes(x = race, fill = race, y = share)) +
  geom_bar(stat = "identity") +
  scale_fill_grey() +
  scale_y_continuous(breaks=c(0,.05,.1)) +
  guides(fill = F) +
  labs(x = "", y = "Proportion") +
  theme_classic() +
  facet_wrap(~ type, nrow = 1) 
```




```{r paper plots}
acc_bper <- tests %>% 
  filter(test_method == "bper") %>% 
  select(test_type, accuracy)

ggplot(acc_bper, aes(x = test_type, y = accuracy, group = 1)) +
  geom_line(color = "darkcyan") +
  geom_point(size = 3, color = "darkcyan") +
  theme_minimal() +
  ylim(0.75, 0.85) +
  labs(y = "Accuracy Score") +
  scale_x_discrete(name = "Model Inputs", limits = rev(c("all", "all_np", "zip", "zip_np", "place", "place_np", "county", "county_np", "state", "state_np")),
                   labels = rev(c(
                     "all" = "Block \n Multi-Unit \n Party ID \n First Name \n Last Name", 
                     "place" = "Place \n Party ID \n First Name \n Last Name", 
                     "county" = "County \n Party ID \n First Name \n Last Name", 
                     "all_np" = "Block \n Multi-Unit \n First Name \n Last Name", 
                     "place_np" = "Place \n First Name \n Last Name", 
                     "county_np" = "County \n First Name \n Last Name",
                     "zip" = "ZIP \n Party ID \n First Name \n Last Name",
                     "zip_np" = "ZIP \n First Name \n Last Name",
                     "state" = "State \n Party ID \n First Name \n Last Name",
                     "state_np" = "State \n First Name \n Last Name"
                   ))) +
  theme(text = element_text(family = "serif"), axis.text.x = element_text(size = 7))

metrics_bper <- tests %>% 
  filter(test_method == "bper") %>% 
  select(test_type, contains(c("prec", "rec"))) %>% 
  pivot_longer(cols = contains(c("prec", "rec"))) %>% 
  separate(name, c("Metric", "Race"), sep = "_") %>% 
  filter(Race != "other") %>% 
  mutate(Metric = case_when(Metric == "prec" ~ "Precision",
                            Metric == "rec" ~ "Recall"),
         Race = case_when(Race == "api" ~ "Asian",
                          Race == "black" ~ "Black",
                          Race == "hispanic" ~ "Hispanic",
                          Race == "white" ~ "White"))

ggplot(metrics_bper, aes(x = test_type, y = value, group = Metric)) +
  geom_line(aes(color = Metric), size = 0.3) +
  geom_point(aes(color = Metric), size = 2) +
  theme_minimal() +
  labs(x = "", y = "Score") +
  scale_color_manual(values = c("gold3", "skyblue4")) +
  scale_x_discrete(name = "Model Inputs", limits = rev(c("all", "all_np", "zip", "zip_np", "place", "place_np", "county", "county_np", "state", "state_np")),
                   labels = rev(c(
                     "all" = "Block", 
                     "place" = "Place", 
                     "county" = "County ", 
                     "all_np" = "Block (np)", 
                     "place_np" = "Place (np)", 
                     "county_np" = "County (np)",
                     "zip" = "ZIP",
                     "zip_np" = "ZIP (np)",
                     "state" = "State",
                     "state_np" = "State (np)"
                   ))) +
  facet_wrap(~ Race) +
  theme(text = element_text(family = "serif"), axis.text.x = element_text(size = 7, angle = 60))

plot_tests <- tests %>% 
  filter(!(test_type %in% c("zip", "zip_np", "state", "state_np")))

accuracy <- plot_tests %>% 
  select(test_method, test_type, accuracy) %>% 
  group_by(test_type) %>% 
  summarise(diff = last(accuracy) - first(accuracy), bper_val = last(accuracy))


ggplot(accuracy, aes(x = test_type, y = diff)) +
  geom_bar(stat = "identity", fill = "darkcyan") +
  theme_minimal() + 
  labs(y = "Difference in Accuracy", x = "") +
  scale_x_discrete(name = "Model Inputs", limits = rev(c("all", "all_np", "place", "place_np", "county", "county_np")),
                   labels = rev(c(
                     "all" = "Block \n Multi-Unit \n Party ID \n First Name \n Last Name", 
                     "place" = "Place \n Party ID \n First Name \n Last Name", 
                     "county" = "County \n Party ID \n First Name \n Last Name", 
                     "all_np" = "Block \n Multi-Unit \n First Name \n Last Name", 
                     "place_np" = "Place \n First Name \n Last Name", 
                     "county_np" = "County \n First Name \n Last Name"))) +
  theme(text = element_text(family = "serif"))
```


```{r paper plots}
api <- plot_tests %>% 
  select(test_method, test_type, prec_api, rec_api) %>% 
  group_by(test_type) %>% 
  summarise(prec_diff = last(prec_api) - first(prec_api), prec_bper = last(prec_api),
            rec_diff = last(rec_api) - first(rec_api), rec_bper = last(rec_api)) %>% 
  ungroup() %>% 
  mutate(prec_color = if_else(prec_diff < 0, "brown", "darkcyan"),
         rec_color = if_else(rec_diff < 0, "brown", "darkcyan"))

prec_api <-
  ggplot(api, aes(x = test_type, y = prec_diff, fill = prec_color)) +
  geom_bar(stat = "identity") +
  scale_fill_identity(guide = F) +
  theme_minimal() + 
  # ylim(0, 0.145) +
  labs(y = "Difference in Precision", x = "", title = "") +
  scale_x_discrete(name = "", limits = rev(c("all", "all_np", "place", "place_np", "county", "county_np")),
                   labels = rev(c(
                     "all" = "", 
                     "place" = "", 
                     "county" = "", 
                     "all_np" = "", 
                     "place_np" = "", 
                     "county_np" = ""))
                   ) +
  theme(text = element_text(family = "serif"))

rec_api <-
 ggplot(api, aes(x = test_type, y = rec_diff, fill = rec_color)) +
  geom_bar(stat = "identity") +
  scale_fill_identity(guide = F) +
  theme_minimal() + 
  # ylim(-0.14, 0.05) +
  labs(y = "Difference in Recall", x = "") +
  scale_x_discrete(name = "Model Inputs", limits = rev(c("all", "all_np", "place", "place_np", "county", "county_np")),
                   labels = rev(c(
                     "all" = "Block \n Multi-Unit \n Party ID \n First Name \n Last Name", 
                     "place" = "Place \n Party ID \n First Name \n Last Name", 
                     "county" = "County \n Party ID \n First Name \n Last Name", 
                     "all_np" = "Block \n Multi-Unit \n First Name \n Last Name", 
                     "place_np" = "Place \n First Name \n Last Name", 
                     "county_np" = "County \n First Name \n Last Name"))) +
  theme(text = element_text(family = "serif"))

grid.arrange(prec_api, rec_api, nrow = 2)
```


```{r paper plots}
black <- plot_tests %>% 
  select(test_method, test_type, prec_black, rec_black) %>% 
  group_by(test_type) %>% 
  summarise(prec_diff = last(prec_black) - first(prec_black), prec_bper = last(prec_black),
            rec_diff = last(rec_black) - first(rec_black), rec_bper = last(rec_black)) %>% 
  ungroup() %>% 
  mutate(prec_color = if_else(prec_diff < 0, "brown", "darkcyan"),
         rec_color = if_else(rec_diff < 0, "brown", "darkcyan"))

prec_black <-
  ggplot(black, aes(x = test_type, y = prec_diff, fill = prec_color)) +
  geom_bar(stat = "identity") +
  scale_fill_identity(guide = F) +
  theme_minimal() + 
  ylim(0, 0.3) +
  labs(y = "Difference in Precision", x = "", title = "") +
  scale_x_discrete(name = "", limits = rev(c("all", "all_np", "place", "place_np", "county", "county_np")),
                   labels = rev(c(
                     "all" = "", 
                     "place" = "", 
                     "county" = "", 
                     "all_np" = "", 
                     "place_np" = "", 
                     "county_np" = ""))
                   ) +
  theme(text = element_text(family = "serif"))

rec_black <-
 ggplot(black, aes(x = test_type, y = rec_diff, fill = rec_color)) +
  geom_bar(stat = "identity") +
  scale_fill_identity(guide = F) +
  theme_minimal() + 
  ylim(-0.3, 0.05) +
  labs(y = "Difference in Recall", x = "") +
  scale_x_discrete(name = "Model Inputs", limits = rev(c("all", "all_np", "place", "place_np", "county", "county_np")),
                   labels = rev(c(
                     "all" = "Block \n Multi-Unit \n Party ID \n First Name \n Last Name", 
                     "place" = "Place \n Party ID \n First Name \n Last Name", 
                     "county" = "County \n Party ID \n First Name \n Last Name", 
                     "all_np" = "Block \n Multi-Unit \n First Name \n Last Name", 
                     "place_np" = "Place \n First Name \n Last Name", 
                     "county_np" = "County \n First Name \n Last Name"))) +
  theme(text = element_text(family = "serif"))

grid.arrange(prec_black, rec_black, nrow = 2)
```


```{r paper plots}
hispanic <- plot_tests %>% 
  select(test_method, test_type, prec_hispanic, rec_hispanic) %>% 
  group_by(test_type) %>% 
  summarise(prec_diff = last(prec_hispanic) - first(prec_hispanic), prec_bper = last(prec_hispanic),
            rec_diff = last(rec_hispanic) - first(rec_hispanic), rec_bper = last(rec_hispanic)) %>% 
  ungroup() %>% 
  mutate(prec_color = if_else(prec_diff < 0, "brown", "darkcyan"),
         rec_color = if_else(rec_diff < 0, "brown", "darkcyan"))

prec_hispanic <-
  ggplot(hispanic, aes(x = test_type, y = prec_diff, fill = prec_color)) +
  geom_bar(stat = "identity") +
  scale_fill_identity(guide = F) +
  theme_minimal() + 
  ylim(0, 0.04) +
  labs(y = "Difference in Precision", x = "", title = "") +
  scale_x_discrete(name = "", limits = rev(c("all", "all_np", "place", "place_np", "county", "county_np")),
                   labels = rev(c(
                     "all" = "", 
                     "place" = "", 
                     "county" = "", 
                     "all_np" = "", 
                     "place_np" = "", 
                     "county_np" = ""))
                   ) +
  theme(text = element_text(family = "serif"))

rec_hispanic <-
 ggplot(hispanic, aes(x = test_type, y = rec_diff, fill = rec_color)) +
  geom_bar(stat = "identity") +
  scale_fill_identity(guide = F) +
  theme_minimal() + 
  ylim(0, 0.04) +
  labs(y = "Difference in Recall", x = "") +
  scale_x_discrete(name = "Model Inputs", limits = rev(c("all", "all_np", "place", "place_np", "county", "county_np")),
                   labels = rev(c(
                     "all" = "Block \n Multi-Unit \n Party ID \n First Name \n Last Name", 
                     "place" = "Place \n Party ID \n First Name \n Last Name", 
                     "county" = "County \n Party ID \n First Name \n Last Name", 
                     "all_np" = "Block \n Multi-Unit \n First Name \n Last Name", 
                     "place_np" = "Place \n First Name \n Last Name", 
                     "county_np" = "County \n First Name \n Last Name"))) +
  theme(text = element_text(family = "serif"))

grid.arrange(prec_hispanic, rec_hispanic, nrow = 2)
```


```{r paper plots}
white <- plot_tests %>% 
  select(test_method, test_type, prec_white, rec_white) %>% 
  group_by(test_type) %>% 
  summarise(prec_diff = last(prec_white) - first(prec_white), prec_bper = last(prec_white),
            rec_diff = last(rec_white) - first(rec_white), rec_bper = last(rec_white)) %>% 
  ungroup() %>% 
  mutate(prec_color = if_else(prec_diff < 0, "brown", "darkcyan"),
         rec_color = if_else(rec_diff < 0, "brown", "darkcyan"))

prec_white <-
  ggplot(white, aes(x = test_type, y = prec_diff, fill = prec_color)) +
  geom_bar(stat = "identity") +
  scale_fill_identity(guide = F) +
  theme_minimal() + 
  ylim(-0.06, 0.02) +
  labs(y = "Difference in Precision", x = "", title = "") +
  scale_x_discrete(name = "", limits = rev(c("all", "all_np", "place", "place_np", "county", "county_np")),
                   labels = rev(c(
                     "all" = "", 
                     "place" = "", 
                     "county" = "", 
                     "all_np" = "", 
                     "place_np" = "", 
                     "county_np" = ""))
                   ) +
  theme(text = element_text(family = "serif"))

rec_white <-
 ggplot(white, aes(x = test_type, y = rec_diff, fill = rec_color)) +
  geom_bar(stat = "identity") +
  scale_fill_identity(guide = F) +
  theme_minimal() + 
  ylim(0, 0.08) +
  labs(y = "Difference in Recall", x = "") +
  scale_x_discrete(name = "Model Inputs", limits = rev(c("all", "all_np", "place", "place_np", "county", "county_np")),
                   labels = rev(c(
                     "all" = "Block \n Multi-Unit \n Party ID \n First Name \n Last Name", 
                     "place" = "Place \n Party ID \n First Name \n Last Name", 
                     "county" = "County \n Party ID \n First Name \n Last Name", 
                     "all_np" = "Block \n Multi-Unit \n First Name \n Last Name", 
                     "place_np" = "Place \n First Name \n Last Name", 
                     "county_np" = "County \n First Name \n Last Name"))) +
  theme(text = element_text(family = "serif"))

grid.arrange(prec_white, rec_white, nrow = 2)
```











```{r}
# Recall investigation

white_wrong <- nc_fl_tests %>% 
  filter(race == "white", pred_race != "white")
black_wrong <- nc_fl_tests %>% 
  filter(race == "black", pred_race != "black")
hispanic_wrong <- nc_fl_tests %>% 
  filter(race == "hispanic", pred_race != "hispanic")
api_wrong <- nc_fl_tests %>% 
  filter(race == "api", pred_race != "api")
other_wrong <- nc_fl_tests %>% 
  filter(race == "other", pred_race != "other")


prop.table(table(white_wrong$pred_race))
nrow(white_wrong)
prop.table(table(black_wrong$pred_race))
nrow(black_wrong)
prop.table(table(hispanic_wrong$pred_race))
nrow(hispanic_wrong)
prop.table(table(api_wrong$pred_race))
nrow(api_wrong)
prop.table(table(other_wrong$pred_race))
nrow(other_wrong)

```

```{r}
# Precision investigation

white_wrong <- nc_fl_tests %>% 
  filter(race != "white", pred_race == "white")
black_wrong <- nc_fl_tests %>% 
  filter(race != "black", pred_race == "black")
hispanic_wrong <- nc_fl_tests %>% 
  filter(race != "hispanic", pred_race == "hispanic")
api_wrong <- nc_fl_tests %>% 
  filter(race != "api", pred_race == "api")
other_wrong <- nc_fl_tests %>% 
  filter(race != "other", pred_race == "other")


prop.table(table(white_wrong$race))
nrow(white_wrong)
prop.table(table(black_wrong$race))
nrow(black_wrong)
prop.table(table(hispanic_wrong$race))
nrow(hispanic_wrong)
prop.table(table(api_wrong$race))
nrow(api_wrong)
prop.table(table(other_wrong$race))
nrow(other_wrong)

```







```{r}
a <- census_geo_api(key = census_api, state = "FL", geo = "county")
```

